robot_cfg_file: lerobot/configs/robot/so100.yaml         # Path to robot yaml file used to instantiate the robot using `make_robot` factory function.


teleop:
  fps: 30                                               # Frames per second (set to None to disable)

record: 
  fps: 30                                               # Frames per second (set to None to disable)
  resume: False                                         # Resume recording on an existing dataset.
  root: data/test                                    # Root directory where the dataset will be stored (e.g. 'dataset/path').
  repo_id: data/test                                 # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
  tags: "custom"                                        # Add tags to your dataset on the hub.
  local_files_only: True                               # Use local files only. By default, this script will try to fetch the dataset from the hub if it exists.
  episode_time_s: 120                                    # Number of seconds for data recording for each episode.
  num_episodes: 1                                       # Number of episodes to record.
  run_compute_stats: True                               # By default, run the computation of the data statistics at the end of data collection. Compute intensive and not required to just replay an episode.
  push_to_hub: False                                    # Upload dataset to Hugging Face hub.
  num_image_writer_processes: 0                         # Number of subprocesses handling the saving of frames as PNGs. Set to 0 to use threads only; set to ≥1 to use subprocesses, each using threads to write images. The best number of processes and threads depends on your system. We recommend 4 threads per camera with 0 processes. If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses. 
  num_image_writer_threads_per_camera: 4                # Number of threads writing the frames as png images on disk, per camera. Too many threads might cause unstable teleoperation fps due to main thread being blocked. Not enough threads might cause low camera fps.
  # pretrained_policy_name_or_path: None                   # Either the repo ID of a model hosted on the Hub or a path to a directory containing weights saved using `Policy.save_pretrained`.
  # policy_overrides: ""
  single_task: "default task"                           # A short but accurate description of the task performed during the recording.

replay:
  fps: 30                                               # Frames per second (set to None to disable)
  root: data/                                           # Root directory where the dataset will be stored (e.g. 'dataset/path').
  repo_id: default/dataset                              # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
  local_files_only: False                               # Use local files only. By default, this script will try to fetch the dataset from the hub if it exists.
  episode: 0                                            # Index of the episode to replay.

calibrate:
  arms: ""                                              # List of arms to calibrate (e.g. `--arms left_follower right_follower left_leader`)"